### ISSUE TITLE
not compatible with matplotlib 3.3.1

### ISSUE THREAD

**Issue by raymondyao** [MatthewReid854/reliability#10]

**Comment by MatthewReid854** [comment]
reliability is not incompatible with matplotlib 3.3.1, it just has >=3.3.2 in the requirements.txt file. It will still operate just fine.

In the most recent release of reliability (0.5.3), I updated the requirements to the most recent versions of all the dependencies. This resulted in some important changes due to scipy and matplotlib, but for the most part is is still largely compatible with much earlier versions than the requirements.txt file specifies.

The biggest issue I've found with the updated dependencies occurs when you try and run reliability in Google Colab which is very stringent about the version of scipy==1.4.1 as well as setting an upper limit on numpy and pandas.

Is there any reason you can't just update your matplotlib to 3.3.2?

**Comment by MatthewReid854** [comment]
I'm closing this issue due to lack of discussion.
If you would like to follow up on this, please email me directly (alpha.reliability@gmail.com).
