### ISSUE TITLE
Random Sampling with numpy.random instead of scipy.stats

### ISSUE THREAD

**Issue by edwardreed81** [MatthewReid854/reliability#13]
You might consider using numpy's random sampling for the distributions it supports because it is significantly faster than scipy's. A brief check indicates that loglogistic is the only one numpy doesn't have built in.

Here's a quick test using a Weibull:

```
%%timeit
fit.distribution.random_samples(1)

54.9 µs ± 2.06 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
```
%%timeit
np.random.weibull(fit.distribution.beta) * fit.distribution.alpha

1.95 µs ± 19.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

Not a huge deal in terms of usability, but if someone is drawing lots of samples (like me) it could be nice.

I'd be happy to do an PR, but it sounds like you're not interested in direct contributions.

**Comment by MatthewReid854** [comment]
Hi Edward,

Thanks for your suggestion.
When evaluating the time taken to draw a large number of random samples it is important that we do a test that is drawing a large number of random samples. Your test draws just 1 sample and by combining the distribution creation (using fit.distribution) in the code there is a lot of extra stuff that reliability is doing to create the distribution object (like finding the mean, median, etc.).
When I run the following code I find that reliability (which uses scipy) beats numpy.

`import numpy as np
from reliability.Distributions import Weibull_Distribution
import time

np.random.seed(1) # just for some repeatability but not really required
samples_required = 100000000 # one hundred million
alpha = 500
beta=2
dist = Weibull_Distribution(alpha=alpha,beta=beta)

start_1 = time.time()
samples_1 = dist.random_samples(samples_required)
stop_1 = time.time()
duration_1 = stop_1-start_1

start_2 = time.time()
samples_2 = np.random.weibull(beta,size=samples_required) * alpha
stop_2 = time.time()
duration_2 = stop_2-start_2

print('Time taken by reliability for',samples_required,'samples:',duration_1)
print('Time taken by numpy for',samples_required,'samples:',duration_2)
print('numpy is',duration_2/duration_1,'times slower than reliability.')`

**Results:**
Time taken by reliability for 100000000 samples: 3.464953899383545
Time taken by numpy for 100000000 samples: 6.626522064208984
numpy is 1.9124416245156735 times slower than reliability.

Based on this result, I will not be making a change from scipy to numpy for the purposes of drawing random samples from distributions.

Regarding your comment about my willingness to accept pull requests, I am quite willing to accept a pull request if it is correct. I have only received a few requests and none of them were ready to integrate into the main body of the code. Of the few I have received, it was faster for me to copy the relevant parts and make the required changes myself than to accept the pull request and then make further changes to what was submitted.
I really appreciate suggestions for how I can improve the library, and if those suggestions are accompanied with code it is even better. Maintaining this library is a lot of work so any help is always welcome.

**Comment by edwardreed81** [comment]
That's really interesting, so I did a little more investigation.

Turns out the numpy method is much faster for smaller sample sizes, while the scipy method is faster as number of samples goes up.
![timing](https://i.imgur.com/rIqdGaU.png)
The crossover seems to be somewhere around `n = 3000`. The code I used to generate this is below.

I'd love to understand the difference in implementations here, but I don't think I want to dive into the numpy and scipy codebases right now.

So if one is pulling large numbers of samples all at once, scipy is faster, but if one needs to pull a relatively small number of samples many times, numpy would be faster. If you wanted to take advantage of this in reliability, you could do something like:

```python
...
if number_of_samples >= 3000:
  RVS = ss.weibull_min.rvs(
              self.beta, scale=self.alpha, loc=self.gamma, size=number_of_samples
          )
else:
  RVS = np.random.weibull(self.beta, size=number_of_samples) * self.alpha
...
```

I wasn't being snarky about the PR. Your CONTRIBUTING.md says:
>I will not accept any merge requests as I wish to retain full rights to the entire codebase.

So I figured you would want to implement any suggestions yourself.


Code for the plot:
```python
import numpy as np
from scipy.stats import weibull_min
import time

alpha = 500
beta=2

nsamples_list = [10**x for x in range(3, 8)]
np_time = []
relia_time = []

for nsamples in nsamples_list:
    niter = int(10e6/nsamples)
    start = time.time()
    [weibull_min.rvs(beta, size=nsamples) * alpha for _ in range(niter)]
    relia_time.append((time.time() - start)/niter)
    start = time.time()
    [np.random.weibull(beta, size=nsamples) * alpha for _ in range(niter)]
    np_time.append((time.time() - start)/niter)

plt.plot(nsamples_list, relia_time, 'o-', label='scipy')
plt.plot(nsamples_list, np_time, 'x-', label='numpy')
plt.xlabel('number of samples')
plt.ylabel('elapsed time')
plt.yscale('log')
plt.xscale('log')
plt.legend()
```

**Comment by MatthewReid854** [comment]
The difference between numpy and scipy here is quite interesting. They must use different algorithms and the scipy team has opted for efficiency on large samples (a smarter choice as that's what takes more time). As for making the change for small sample sizes, your suggestion would be an improvement but we are talking microsecond difference here so I think it is inconsequential unless you are doing a small number of samples millions of times.

Thanks for pointing out the line in my CONTRIBUTING.md file. I wrote that a long time ago and I have since changed my mind (it is now updated). I welcome contributions of code, both in email and as pull requests. I prefer to treat GitHub as my "master" copy and have my working copy on my computer which I push to GitHub when I'm ready. This ensures that anyone who git clones my repo always gets something that works rather than something that is still under construction or hasn't been tested. I know most repos don't work this way and as they grow to larger number of contributors it becomes impossible to work this way. While my number of contributors remains small I prefer to accept submissions via email so that I can test them myself before pushing to GitHub. I have nothing against accepting pull requests, I just prefer to use a different workflow to integrate contributions.

I know you'll probably think, why not just use automated tests to do the testing. This is true for existing code but automated tests can't test new functions. Also, improvements may change the results for the better so simply checking that the result is the same may not be enough. I might need a monte carlo simulation to verify an improvement. Also, on the topic of tests, I recently (v0.5.5) made a big change to Fitters which did change all the results for the better. Consequently, I deactivated many of the tests as they were incorrect after 5 or 6 decimal places. I need to recalibrate many of the tests so at this stage only the Distributions module is being tested. If you want to help with something, I would be happy to receive help rewriting the tests. Email me if you want to work on this.
