### ISSUE TITLE
Fit a three parameter reversed Weibull distribution.

### ISSUE THREAD

**Issue by paweller** [MatthewReid854/reliability#15]
Hello everyone,

Firstly, I want to thank @MatthewReid854 for his outstanding work on this entire library. I am blown away by the fact that he is a "one-man-band" for this entire repository.

I am currently working on a class-inclusion probability model. My goal is to determine how likely it is that a given sample belongs to a specific class. To get this class-inclusion probability model working, I need to fit one three parameter reversed Weibull distribution to each class. I am new to the whole reliablitiy engineering topic and therefore lacking an understanding of what the meaning of the reversed Weibull distribution in comparison to the normal one is. I am wondering whether I can use the `Fit_Weibull_3P` function to fit the reversed Weibull distribution (see formula below) as well?

![image](https://user-images.githubusercontent.com/77730889/107993815-a9aadc00-6fdb-11eb-980e-622b7f5bc00b.png)

**Comment by MatthewReid854** [comment]
Hi Paweller,

I'm glad to hear you find this library useful. As you can imagine it is a lot of work to develop but it is something I enjoy doing. About 99% of the code is written by me but I have had help from several key [individuals](https://reliability.readthedocs.io/en/latest/Credits%20to%20those%20who%20helped.html) who deserve to be acknowledged.

Until I read your question, I had never heard of the reversed Weibull distribution. From what I have read, it is not very popular and has limited applications in reliability engineering which is why it is not part of this library. It's typical use is as a "smallest extreme value" distribution putting it in the same category as the Gumbel and Frechet distributions. Note that Fit_Gumbel_2P is part of the library so you might want to try that.
The Weibull Distribution has a domain from 0 to +infinity. This is useful in reliability engineering since we typically say that time (or cycles, km, miles, rounds, etc.) can't be negative.
The reversed Weibull distribution is a modification of the Weibull distribution with a few extra negative signs such that the distribution has a domain of -infinity to 0. Effectively it's a Weibull distribution that has been mirrored (reversed) about the vertical axis.

So, to answer your question, no you can't use Fit_Weibull_3P to fit the reversed Weibull distribution directly as it is an entirely different distribution. You could conceivably reverse your data (by flipping all it's signs) and then use Fit_Weibull_3P (or Fit_Weibull_2P if it's not location shifted). Once you have fitted the distribution, you can't simply reverse the distribution with a negative sign (as that'd flip it vertically not horizontally) so you'll need to define the equation of the distribution yourself and insert the fitted parameters. I haven't tried this myself so no guarantees it'll work, but that's my suggestion.

Your "issue" is really a question not an issue so for any future questions please direct them via email to alpha.reliability@gmail.com. GitHub issues should be used for bugs or improvements.
