### ISSUE TITLE
Strage results from `Fit_Weibull_3P`

### ISSUE THREAD

**Issue by tkarkkainen** [MatthewReid854/reliability#25]
First of all, congratulations on the awesome work! Up until now I've been using Matlab for similar things, but thanks to this package I've been able to do stuff more easily now!

I'm not sure if this is a bug or a misunderstanding on my part on how the three-parameter Weibull is fitted, but I am getting some strange results with a low number of samples. Here's a minimal working example:

```python
from reliability.Fitters import Fit_Weibull_3P

fit = Fit_Weibull_3P(failures=[500, 600, 700, 800])
```

I am under the impression that each data point on the plot should be located similarly to how things work with `Fit_Weibull_2P()`: each point placed at the failure time, i.e. at 500, 600, 700 and 800 on the horizontal axis in the example above. The first point is, however, located at 1e-4, and this seems to happen whenever there are four or five items in the `failures` list. The following points are not located at the values specified by the `failures` list either.

Output from the code above:
![Screenshot 2021-12-17 at 15 03 34](https://user-images.githubusercontent.com/28619014/146548701-2302257d-3c08-45e9-9adf-b4d7fa1bf9f0.png)

Is this a bug or a misunderstanding on my part?

**Comment by MatthewReid854** [comment]
It's not a bug, just the deceptive nature of having the x-axis being "Time-gamma" displayed on a log scale. The horizontal distance between the CDF and the first failure point is actually quite small, but it appears big because of the log scale.
Here's the probability plot shown alongside the CDF on linear axes.
![Figure_1](https://user-images.githubusercontent.com/35417895/146637216-e9028429-04bc-40e7-857b-ec3b09069727.png)

As for your comment about the failure points not being located at the failure times, this is again because the x-axis is "Time-gamma". If the x-axis is "Time" rather than "Time-gamma" then the CDF is no longer linear for location shifted distributions like Weibull_3P.

**Comment by tkarkkainen** [comment]
Thank you. It makes so much sense now. I was quite sure there was something wrong with my thinking. I don't know how I interpreted "Time - gamma" but I certainly did not understand it to mean "Time *minus* gamma".

**Comment by MatthewReid854** [comment]
I'm glad I could clear things up for you.
If you have any suggestions on how I could improve the documentation, please email me (alpha.reliability@gmail.com).
