### ISSUE TITLE
Possible issue with the quad function for interference calculation

### ISSUE THREAD

**Issue by Tyrin451** [MatthewReid854/reliability#8]
Hello,

The scipy.quad function used to calculate the probability of failures miss to compute the interference area.

I have the following code :

```
stress = Lognormal_Distribution(mu=9.826147748745854,sigma=0.16739388240778247)
strength = Normal_Distribution(mu=189000,sigma=34020)
result = Probability_of_failure(stress=stress, strength=strength, show_distribution_plot=False)
Probability of failure: 1.550966899579015e-77
```

But when I manually use np.trapz a have :

```
x=np.arange(0,300e3,10)
interf = stress.PDF(x, show_plot=False) * strength.CDF(x, show_plot=False)
np.trapz(interf,x)
3.171812771218649e-07
```

I suspect the quad function to evaluate the interval 0 to 1 only on some point and miss the interference.

May be the range of the data I use have an impact on this effect. I don't know. May be I'm wrong.
Can you enlighten this behavior ?

Thank you.

**Comment by MatthewReid854** [comment]
@TEFEdotcc might be able to help as he kindly wrote this integral for me.

I'm not certain exactly why this occurs. It's probably related to the accuracy of the method used.
Based on the two different outputs it is clear that there is almost no interference (around 3e-7) so perhaps the amount of interference is less than the accuracy of each method.

**Comment by TEFEdotCC** [comment]
Hello Tyrin451,
Hello Matthew,

today I do an quick check and yes, it is a very special case. The case itself occurs two problems

1. The quad functions absolute error is set to 1e-4 and the integration value is round about 3e-7. So inside the absolute error. The function to the job correctly :)
1. There is a very small range 1e4 to 3e4 and strange position, where the interference function (cdf * pdf) has values that are important for the integration.

My working example for the issue with current version _reliability-0.5.2_.
```python
# -*- coding: utf-8 -*-

import matplotlib
import matplotlib.pyplot as plt
import numpy as np

from scipy.integrate import quad, quadrature

from reliability.Distributions import Lognormal_Distribution, Normal_Distribution
from reliability.Stress_strength import Probability_of_failure

# library
stress = Lognormal_Distribution(mu=9.826147748745854,sigma=0.16739388240778247)
strength = Normal_Distribution(mu=189000,sigma=34020)
result = Probability_of_failure(stress=stress, strength=strength, show_distribution_plot=False)
# Probability of failure: 1.550966899579015e-77

# trapez rule
xlimit = 1e6
x=np.arange(0,xlimit,1000)
pdf = stress.PDF(x, show_plot=False)
cdf = strength.CDF(x, show_plot=False)
interf = pdf * cdf
result = np.trapz(interf,x)
# Probability of failure: 3.1718127712186513e-07

print("Probability of failure: {0}".format(result))

fig, ax = plt.subplots()
ax.plot(x, pdf, label = "pdf")
ax.plot(x, cdf, label = "cdf")
ax.plot(x, interf, label = "interference")
plt.legend()
plt.show()

# check library enhancement
def failure(stress, strength, x_start = None, x_end = None, points_of_difficults = None):
    func = lambda x: stress.PDF(x, show_plot=False) * strength.CDF(x, show_plot=False)
    start = 0.0
    end = np.inf
    
    if x_end:
        end = x_end
    elif points_of_difficults:
        end = 1e9
        
    if x_start:
        start = x_start
        
    if not points_of_difficults:
        return quad(func, start, end, epsabs=1.0e-3, epsrel=1.0e-5, limit=100)
    else:
        return quad(func, start, end, epsabs=1.0e-3, epsrel=1.0e-5, limit=100, points=points_of_difficults)

result = failure(stress, strength)
# Probability of failure: 1.151128469953109e-112 (err: 2.2758554377723555e-112)
print("Probability of failure: {0} (err: {1})".format(result[0], result[1]))

result = failure(stress, strength, points_of_difficults = (1e4, 2e4, 3e4))
# Probability of failure: 3.134809435783137e-07 (err: 3.308386617781766e-17)
print("Probability of failure: {0} (err: {1})".format(result[0], result[1]))

result = failure(stress, strength, x_end = 1e6)
# Probability of failure: 4.0966937850601855e-07 (err: 7.861400348473751e-07)
print("Probability of failure: {0} (err: {1})".format(result[0], result[1]))

result = failure(stress, strength, x_end = 1e6, points_of_difficults = (1e4, 2e4, 3e4))
# Probability of failure: 3.172655781016679e-07 (err: 7.465491186522927e-09)
print("Probability of failure: {0} (err: {1})".format(result[0], result[1]))
```
 
@MatthewReid854 
Followed enhancement I would do to handle cases like that

1. The quad function can also handle integrals from 0 to inf. So, the actuall integral transformation from [0;inf[ to [0;1] is not needed. ```np.inf``` can be used for the right integral border.
Check out the `failure` function above.
1. The parameter **epsabs** is optional an I think we should not set it. The default value is a good point if values near 1.0 are expected
1. For the relative error it should be added a new optinal parameter, if cases can be profit for an different value. (Integration to inf is in the most cases not needed. Set intervalls like [0;1e5], ... could help the adaptive algorithmus to find small jumps. Like that case)
1. For cases like that it could be also help to set the **lower** and/or **upper** bound of the integral.
1. The quad function also support to specify points of difficults (e.g. singularity, ...). It should also possible to specify that points.
1. It should also be possible to get the error of the integration. (second value of quad function). If the error is not lesser than 1e-1 ...1e-3 of the result, the result should be checked very carefull.

@Tyrin451 
Thank you for share our case with us. It should be helping to improve the integration function.
I hope my working example introduce a idea to fix your case as long as the fix is in a new release.

**Comment by TEFEdotCC** [comment]
@Tyrin451 
I do not look to the math. Can you deliver a analytic solution to your case?

**Comment by MatthewReid854** [comment]
@TEFEdotCC
Thanks for this detailed response. I think we all agree that the error is small, but it is desirable to make it as small as possible. Any change to the code needs to handle special cases (points_of_difficults as you called them) automatically. Many users of this library will understand what stress strength interference is but they may not understand how the integration algorithms work. With this in mind, I will not change the code in a way that requires any extra user inputs.

If you have some example code that deals with special cases automatically, I will take a look.

**Comment by MatthewReid854** [comment]
@TEFEdotCC and @Tyrin451
The only way I can be sure of the true answer is to compare them with the normal distribution exact formula. Can you please take a look at the following and tell me if you think it is a suitable replacement / change to the code:

`from reliability.Distributions import Normal_Distribution
from reliability.Stress_strength import Probability_of_failure, Probability_of_failure_normdist
import numpy as np
import matplotlib.pyplot as plt

stress = Normal_Distribution(mu=20, sigma=20)
strength = Normal_Distribution(mu=300, sigma=20)

exact = Probability_of_failure_normdist(stress=stress, strength=strength, show_distribution_plot=False, print_results=False)
res1 = Probability_of_failure(stress=stress, strength=strength, show_distribution_plot=True, print_results=False, warn=False)
print('Error in current method:', abs(exact - res1))

x = np.linspace(stress.quantile(1e-8), strength.quantile(1-1e-8), 1e5)
res2 = np.trapz(stress.PDF(x, show_plot=False) * strength.CDF(x, show_plot=False), x)
print('Error in new method:', abs(exact - res2))
plt.show()`

OUTPUT:
Error in current method: 7.061195738970259e-23
Error in new method: 2.2334392665623463e-37

**Comment by Tyrin451** [comment]
@TEFEdotCC 
No, I have no analytical solution. 
I can only compare the result with another python reliability library, pyre, which use monte-carlo process. (This library is more complex and a prefer reliability for my "simple" case.)

@MatthewReid854 
This approach seems to work. I wonder if we could estimate the sampling to use, instead of brutally take 1e5 values.

For sure, the probabily of failure of 10e-7 is very low. But It is in the order what I would. And I need accuracy at these amplitude to discriminate what loadings is the worst.

Thanks for the looking :) if it may help.

**Comment by MatthewReid854** [comment]
@Tyrin451
The monte carlo approach is less reliable than the integral approach for 2 reasons. It requires many samples to be accurate resulting in a very slow calculation if you want an accurate answer, and it is based on random sampling so the answer will change each time as the random seed changes. The Python reliability library originally used MC sampling in this function until @TEFEdotCC  showed me the integral method.

As for which integral method (trapz or quad) is more accurate, the only way we have to know is comparison with the 
exact result which can be performed for the Normal distribution only. When this is done, it is clear that the new method is much better (by about 15 orders of magnitude). This improvement is less as the probability of failure increases (ie. as the interference region gets much larger due to stress getting closer to strength).

Based on the plot below, I will be changing the method to the new method proposed by @Tyrin451 
Let me know if either of you have any issues with this.

![image](https://user-images.githubusercontent.com/35417895/93072944-7dee9780-f6c5-11ea-981a-cc1069b2dede.png)

Code to produce this image (takes about 1 minute to run):
`from reliability.Distributions import Normal_Distribution
from reliability.Stress_strength import Probability_of_failure, Probability_of_failure_normdist
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

mu2 = np.linspace(-50,300,500)
stress = Normal_Distribution(mu=20, sigma=20)
exact_array = []
currentmethod_array = []
newmethod_array = []

for m in tqdm(mu2):
    strength = Normal_Distribution(mu=m, sigma=20)
    exact = Probability_of_failure_normdist(stress=stress, strength=strength, show_distribution_plot=False, print_results=False)
    exact_array.append(exact)
    res1 = Probability_of_failure(stress=stress, strength=strength, show_distribution_plot=False, print_results=False, warn=False)
    currentmethod_array.append(abs(exact - res1))

    x = np.linspace(stress.quantile(1e-8), strength.quantile(1-1e-8), 1000)
    res2 = np.trapz(stress.PDF(x, show_plot=False) * strength.CDF(x, show_plot=False), x)
    newmethod_array.append(abs(exact - res2))
plt.plot(exact_array,currentmethod_array,label='current method error')
plt.plot(exact_array,newmethod_array,label='new method error')
plt.axvline(x=1,color='k')
plt.yscale('log')
plt.xscale('log')
plt.legend()
plt.xlabel('Exact probability of failure')
plt.ylabel('Error in integral methods')
plt.title('Comparison of methods\nbased on probability of failure')
plt.show()`

**Comment by TEFEdotCC** [comment]
The new method looks good, but I'm not sure if a fixed step size (1e5 in that example) is a good idea. Maybe it works in most examples, but I think there are also test cases in that the method will fail.
An error estimation + step size correction should be implemented.

Of course the integration function *quad* is very old. A alternative method is postulated in **NUMERICAL RECIPES**, *3 rd. Edition, Chapter 4.7 "Adaptive Quadrature"*. The lowest degree of integration (in worst cases) would be degree 4 and is exact for polynomails of order 5. If I had time I would implement and test it in the next time (weeks).

Another automatic improvment would be the intersection point of the two functions.
Is there always one intersection point of stress.pdf and strength.cdf function?

**Comment by MatthewReid854** [comment]
I have not found a case where the trapz method fails despite testing several different distributions and hundreds of thousands of combinations of parameters in a monte carlo analysis. If you find a case where it fails, please let me know. Until then I will implement the new method as part of version 0.5.3 (due for release in the next 1-2 weeks).

To answer your question "Is there always one intersection point of stress.pdf and strength.cdf function": Provided the stress << strength then yes there is only one intersection. You could easily conceive a situation where this is not the case if the distributions are almost overlapping. Such cases should be rare in practice as stress-strength interference is usually analysed when there is only a small region of interference, otherwise failure of the component is highly likely.

Thanks for your discussion on this. I'll now close this issue.
