### ISSUE TITLE
Reliability_testing returns that its functions are not defined

### ISSUE THREAD

**Issue by pedrodamas0803** [MatthewReid854/reliability#9]
Hi, 
I am using the package to model some failure data for research purposes. I had success with all the modules and they are working great. Except for the Reliability_testing that is returning that its functions are not defined. I tried using both KStest and chi2test and jupyter notebook returns that they are not defined. Also, I looked at the original code, I was able to follow the steps but couldn't tell where is this error coming from. I tried reinstalling the package to fix any error in the previous installation but it didn't work. 
Here is a print of the error. All distributions were imported when I ran this piece of code. And the distribution that I used as input was generated with the parameters I found using the Fitter module.

![image](https://user-images.githubusercontent.com/63425375/95018049-57bc7780-0633-11eb-9bd1-32eebcb65f8b.png)

Thanks!
Pedro

**Comment by MatthewReid854** [comment]
Hi Pedro,

Please enter the following command:
```
from reliability import __version__
print(__version__)
```

If your answer is not 0.5.3 then you need to upgrade your version to the most recent version since KStest and chi2test were only implemented in version 0.5.3.

If you do have the most recent version then please enter the example for KStest exactly as it is given in the [documentation](https://reliability.readthedocs.io/en/latest/Kolmogorov-Smirnov%20test.html) and provide the full output/traceback of any errors that are printed to console.

Thanks.

**Comment by pedrodamas0803** [comment]
Hi Mathew, 

I had read the changelog and updated the package through jupyter notebook. As the code accepted the part where I imported everything I assumed that it was in the correct version. Now I checked the version via terminal with pip and it was in version 0.5.2.
Sorry to bother with this kind of mistake, and thank you for your attention. 

Pedro
